export const projects = [
  {
    slug: 'sempaihq',
    title: 'SempaiHQ - Decentralized Anime Platform',
    description: 'Fully decentralized Web3 platform for anime creators and fans with integrated Solana wallet, token economy, and interactive features.',
    longDescription: 'SempaiHQ is a groundbreaking fully decentralized Web3 application built on Solana blockchain, revolutionizing the anime creators community. Users can create in-app Solana wallets or connect external wallets (Phantom, Solflare) with Google authentication for enhanced security. The platform features a token-based economy where users claim tokens to access premium anime novels and manga content. Comprehensive features include: interactive anime novels and manga library, integrated crypto wallet for sending/receiving tokens and SOL, real-time chat system, community polls and voting, Kaito Adventure Game (on-chain gaming), and creator monetization tools. Available as both web dApp and mobile application with cross-platform wallet synchronization.',
    tech: ['Next.js', 'Solana', 'Rust', 'Anchor', 'React Native', 'Web3.js', 'TypeScript', 'PostgreSQL', 'Redis'],
    github: '',
    live: 'https://sempaihq.xyz',
    image: '/projects/sempaihq.png',
    status: 'live',
    year: 2024,
    highlights: [
      'Fully decentralized on Solana blockchain',
      'In-app wallet creation & external wallet integration',
      'Token-based content access system',
      'Multi-platform (Web dApp + Mobile)',
      'Real-time chat & community features',
      'On-chain Kaito Adventure Game',
      'Creator monetization & royalty distribution',
      'Google-secured wallet authentication',
    ],
  },
  {
    slug: 'virginiacakes',
    title: 'Virginia Cakes & Confectioneries',
    description: 'Premium e-commerce platform for custom cakes and innovative confectioneries with nationwide delivery.',
    longDescription: 'Virginia Cakes & Confectioneries is a sophisticated e-commerce platform specializing in custom cakes, pastries, and innovative confectionery products. Built with modern web technologies, the platform offers seamless ordering experiences with real-time inventory management, secure payment processing, and nationwide delivery tracking. Features include: custom cake designer with real-time preview, extensive product catalog with detailed descriptions and allergen information, secure checkout with multiple payment options, order tracking and delivery scheduling, customer reviews and ratings, admin dashboard for inventory and order management, and automated email notifications for order updates.',
    tech: ['Next.js', 'React', 'TypeScript', 'Stripe', 'PostgreSQL', 'TailwindCSS', 'Vercel', 'AWS S3'],
    github: '',
    live: 'https://virginiacakes.vercel.app',
    image: '/projects/virginiacakes.png',
    status: 'live',
    year: 2024,
    highlights: [
      'Custom cake designer tool',
      'Nationwide delivery network',
      'Secure payment integration',
      'Real-time order tracking',
      'Mobile-responsive design',
      'Admin inventory management',
      'Customer review system',
      'Automated notifications',
    ],
  },
  {
    slug: 'digitec',
    title: 'DigiTec Learning Platform',
    description: 'Comprehensive online learning platform offering tech courses from computer basics to advanced development, data analysis, and creative skills.',
    longDescription: 'DigiTec is a modern e-learning platform similar to Coursera, providing high-quality tech education across multiple domains. The platform offers structured courses in: Computer Basics and Fundamentals, Frontend Development (HTML, CSS, JavaScript, React), Backend Development (Node.js, Python, Django, APIs), Data Analysis and Visualization, Forex Trading and Financial Markets, Graphic Design and UI/UX, Digital Marketing, and more. Features include: interactive video lessons with progress tracking, hands-on coding exercises and projects, certificate of completion, instructor Q&A forums, mobile-friendly learning experience, course marketplace for instructors, payment processing for premium courses, and personalized learning paths based on skill level.',
    tech: ['Next.js', 'React', 'TypeScript', 'Node.js', 'PostgreSQL', 'AWS', 'Stripe', 'TailwindCSS'],
    github: '',
    live: 'https://digitec-gamma.vercel.app',
    image: '/projects/digitec.png',
    status: 'live',
    year: 2024,
    highlights: [
      'Multi-domain course catalog',
      'Interactive video learning',
      'Hands-on coding exercises',
      'Progress tracking & certificates',
      'Instructor marketplace',
      'Mobile-optimized interface',
      'Community forums',
      'Personalized learning paths',
    ],
  },
  {
    slug: 'ledgerquantumvault',
    title: 'Ledger Quantum Vault',
    description: 'Advanced cryptocurrency broker platform with secure trading, multi-chain support, and institutional-grade security.',
    longDescription: 'Ledger Quantum Vault is a professional-grade cryptocurrency brokerage platform providing secure trading services for digital assets. Built with enterprise security standards, the platform offers: multi-chain cryptocurrency trading (Bitcoin, Ethereum, Solana, and more), real-time market data and advanced charting tools, secure wallet integration with cold storage options, institutional-grade security with 2FA and biometric authentication, automated trading bots and strategies, portfolio analytics and performance tracking, competitive trading fees and liquidity, and 24/7 customer support. The platform prioritizes security and user experience, making crypto trading accessible to both beginners and professional traders.',
    tech: ['Next.js', 'Web3.js', 'Solana', 'Ethers.js', 'React', 'TypeScript', 'Node.js', 'PostgreSQL', 'Redis'],
    github: '',
    live: 'https://ekene-broker.vercel.app',
    image: '/projects/ekenebroker.png',
    status: 'live',
    year: 2024,
    highlights: [
      'Multi-chain crypto trading',
      'Institutional-grade security',
      'Real-time market analytics',
      'Cold storage integration',
      'Automated trading strategies',
      'Advanced charting tools',
      'Low trading fees',
      '24/7 support',
    ],
  },
  {
    slug: 'wlfi',
    title: 'WLFI',
    description: 'Next-generation crypto trading platform with AI-powered insights, DeFi integration, and social trading features.',
    longDescription: 'WLFI Broker is an innovative cryptocurrency trading platform that combines traditional brokerage services with cutting-edge DeFi integration. The platform leverages AI and machine learning to provide: intelligent trading signals and market predictions, seamless DeFi protocol integration for yield farming, social trading features to follow top traders, cross-chain asset swaps and bridging, advanced risk management tools, NFT marketplace integration, staking and liquidity mining opportunities, and comprehensive portfolio management. Marv Broker aims to democratize crypto trading by making complex DeFi strategies accessible through an intuitive interface while maintaining professional-grade features for experienced traders.',
    tech: ['Next.js', 'Web3.js', 'Solana', 'React', 'TypeScript', 'Python', 'TensorFlow', 'PostgreSQL', 'GraphQL'],
    github: '',
    live: 'https://marvbroker.vercel.app',
    image: '/projects/marvbroker.png',
    status: 'live',
    year: 2024,
    highlights: [
      'AI-powered trading signals',
      'DeFi protocol integration',
      'Social trading platform',
      'Cross-chain swaps',
      'NFT marketplace access',
      'Staking & yield farming',
      'Risk management tools',
      'Copy trading features',
    ],
  },
  {
    slug: 'web3broker',
    title: 'Web3 Broker',
    description: 'User-friendly cryptocurrency exchange with focus on emerging markets, peer-to-peer trading, and educational resources.',
    longDescription: 'Web3 Broker is a cryptocurrency exchange platform designed with emerging markets in mind, providing accessible crypto trading with local payment methods and peer-to-peer capabilities. The platform features: P2P trading with escrow protection, local currency support for multiple regions, educational resources and trading guides for beginners, low-fee structure optimized for smaller transactions, mobile-first design for accessibility, instant buy/sell with local payment methods, secure KYC verification, community-driven support and tutorials, and merchant payment solutions. Ekene Broker focuses on financial inclusion, making cryptocurrency accessible to users in regions with limited traditional banking infrastructure.',
    tech: ['Next.js', 'React', 'Web3.js', 'Node.js', 'MongoDB', 'Socket.io', 'TailwindCSS', 'Stripe', 'PayPal'],
    github: '',
    live: 'https://web3broker.vercel.app',
    image: '/projects/web3broker.png',
    status: 'live',
    year: 2024,
    highlights: [
      'P2P trading with escrow',
      'Local currency support',
      'Beginner-friendly interface',
      'Mobile-first design',
      'Educational resources',
      'Low transaction fees',
      'Merchant payment integration',
      'Community support',
    ],
  },
];

export function getProjectBySlug(slug) {
  return projects.find((project) => project.slug === slug);
}

export function getAllProjects() {
  return projects;
}
